//
//  DetailInteractor.swift
//  SmartFetcher
//
//  Created by Raymond Law on 9/1/17.
//  Copyright (c) 2017 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Business logic

protocol DetailBusinessLogic
{
  func showEvent(request: Detail.ShowEvent.Request)
  var event: Event? { get set }
}

// MARK: - Data store

protocol DetailDataStore
{
  var event: Event? { get set }
}

// MARK: - Interactor

class DetailInteractor: DetailBusinessLogic, DetailDataStore
{
  var presenter: DetailPresentationLogic?
  var event: Event?
  
  // MARK: - Show event
  
  func showEvent(request: Detail.ShowEvent.Request)
  {
    if let event = event {
      let response = Detail.ShowEvent.Response(event: event)
      presenter?.presentEvent(response: response)
    }
  }
}
